### ISSUE TITLE
Seurat3 object

### ISSUE THREAD

**Issue by akhst7** [SGDDNB/GeneSwitches#1]
HI, 

Is there an example script to import Seurat3 (instead of Monocle) object into GeneSwithes and go through the same level of analysis ? 

Thanks.

**Comment by YiqunCao** [comment]
Hi @akhst7,

Thanks for using GeneSwitches.

Here is an example to extract required information from Seurat3 object. PC1 cell distribution is used as the psudotime here, but you may input your own vector as pseudotime.

`logexpdata <- seurat_obj@assays$integrated@data`
`cell_pseudotime <- Embeddings(object = seurat_obj, reduction = "pca")[, "PC_1"]`
`rd_UMAP <- Embeddings(object = seurat_obj, reduction = "umap")`

With these information, we can create a SingleCellExperiment object as follows.

`sce <- SingleCellExperiment(assays = List(expdata = logexpdata))`
`colData(sce)$Pseudotime <- cell_pseudotime`
`reducedDims(sce) <- SimpleList(UMAP = rd_UMAP)`

Then `sce` can be used to run GeneSwitches from PART I. of the tutorial.

**Comment by KinSimon96** [comment]
Hello,

I was about to ask the same question but this subject is already on. I followed your code and when I'm running:
`sce_p1 <- binarize_exp(sce, ncores = 1)`
I get the following message after some minutes:
`Error in t.default(binLogCounts) : argument is not a matrix`

Do you know how to solve it ? 
In advance, thank you!
Simon

**Comment by YiqunCao** [comment]
Hi Simon,

Thanks for using GeneSwitches.

Hope that you can receive my reply here, I somehow cannot find your question in github issues.

Anyway, sorry that I cannot reproduce your error. Could you please provide slightly more information about your Seurat object?

Alternatively, you may try using a global threshold for binarization as described in the tutorial, for example,

        sce_p1 <- binarize_exp(sce_p1, fix_cutoff = TRUE, binarize_cutoff = 0.2, ncores = 1)


Best,
Yiqun


________________________________
