### ISSUE TITLE
convert_monocle2 

### ISSUE THREAD

**Issue by colin986** [SGDDNB/GeneSwitches#2]
Hi, 

this function seems to have an error 

 rd <- t(cardiac_monocle2@reducedDimS)[rownames(cells), ]

should this line be:
  rd <- t(monocle2_obj@reducedDimS)[rownames(cells), ]

Colin

**Comment by YiqunCao** [comment]
Hi @colin986 ,

Thanks for using GeneSwitches.
The error has been fixed. Sorry.

**Comment by colin986** [comment]
Thanks @YiqunCao!
