### ISSUE TITLE
Error in oupBinary$mu2 - oupBinary$mu1 :    non-numeric argument to binary operator

### ISSUE THREAD

**Issue by Puriney** [SGDDNB/GeneSwitches#3]
Hello, I was running the `binarize_exp()` using gene-specific thresholds. But I came across with the error which is related to this code line: https://github.com/SGDDNB/GeneSwitches/blob/b1824e467ad66b2c071b9207f45890ece7b3dd53/R/binarization.R#L76

```
Error in oupBinary$mu2 - oupBinary$mu1 : 
  non-numeric argument to binary operator
```

When I check the warnings, here is one line:

```
In `[<-.factor`(`*tmp*`, ri, value = "Error in normalmixEM(LogCountsadd[iGene, ], k = 2) : Too many tries!\n") :
  invalid factor level, NA generated
```

I am thinking this must be my data problem. Could it because some gene in my data just has a flat expression across all cells, e.g., all 10s or 0s in all cells?

**Comment by Puriney** [comment]
oupBinary is a data frame having those column names and each row is gene.

geneID,  mu1, mu2, sigma1, sigma2, lambda1, lambda2, loglik

It seems some genes in my data have non-numeric mu1 and mu2 values.

**Comment by Puriney** [comment]
`binarize_exp` technically works if I use a global threshold.

**Comment by Puriney** [comment]
thx

**Comment by YiqunCao** [comment]
Hi @Puriney ,

Thanks for using GeneSwitches and helping fix the errors. I realized that it would cause downstream errors if we add NAs, so I changed back to the original version first.

It is recommended to remove genes with extremely low expression (i.e. all zeros) before running GeneSwitches. For example, you may use the following code to only keep genes with an expression level above 0 in at least 5 cells.
`expdata <- expdata[apply(expdata > 0, 1, sum) >= 5, ]`

**Comment by moi-taiga** [comment]
I was experiencing the same error as @Puriney described above.

When trying to use  `expdata <- expdata[apply(expdata > 0, 1, sum) >= 5, ]` to solve the issue,
I am faced with a new error:

Error in fixupDN.if.valid(value, x@Dim) :
  length of Dimnames[[1]] (17769) is not equal to Dim[1] (17183)
Calls: binarize_exp ... <Anonymous> -> dimnames<- -> dimnames<- -> fixupDN.if.valid

**Comment by moi-taiga** [comment]
Or if i remove low expression another way:

`expression_threshold <- 0
min_cells_threshold <- 5
cells_per_gene <- rowSums(assay(sce) > expression_threshold)

# Subset the SingleCellExperiment object to keep only genes with expression > 0 in at least min_cells_threshold cells
sce <- sce[cells_per_gene >= min_cells_threshold, ]`

I get the following error:
Error in `$<-.data.frame`(`*tmp*`, "passBinary", value = FALSE) :
  replacement has 1 row, data has 0
Calls: binarize_exp -> $<- -> $<-.data.frame
